### PR TITLE
Update image list in READMEs automaticly & other minor changes

### PR DESCRIPTION
**Pull request by lgc2333**
# Pull Request

## Description

- Refactor generate README script
- Auto update READMEs using GitHub Action
- reformat READMEs & other docs
- Move `ReplaceGuide` to `docs` folder

## Related Issues

_None_

## Pictures (if applicable)

_None_

## Checklist

- [x] I have tested the changes/updates before submitting this pull request.

## Additional Notes

_None_

### CODE REVIEW

**Comment by ahmedredhat** [comment]
Her

**Comment by ahmedredhat** [comment]
<a href=http://evil.com>here </a>


[http://evil.com](url)

**Comment by ahmedredhat** [comment]
<a href=http://google.com>here </a>


[http://google.com](url)

**Review by T-taku — APPROVED** [review]
LGTM:):)

**Comment by ahmedredhat** [comment]
<a href=http://evil.com>here </a>

**Pull request merged**
